#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Ashwin Vishnu <ashwinvis plus gh @t protonmail D0T com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

HISTFILE=${ZDOTDIR:-$HOME}/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch
unsetopt beep
# End of lines configured by zsh-newuser-install

# Custom zsh completions
fpath=($HOME/.local/etc/zsh_completion.d $fpath)

# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' matcher-list '' 'm:{[:lower:]}={[:upper:]}' 'l:|=* r:|=*'
zstyle :compinstall filename '${ZDOTDIR:-$HOME}/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# zsh-autosuggestions bind
bindkey '^ ' autosuggest-accept

# Alias
alias tr='noglob tr'

# System-specific customizations

if [ -f ${ZDOTDIR:-$HOME}/.zsh_profile ]; then
  source "${ZDOTDIR:-$HOME}/.zsh_profile"
fi
