# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#!zsh
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Ashwin Vishnu <ashwinvis plus gh @t protonmail D0T com>
#
# Profile
# zmodload zsh/zprof

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# System-specific customizations
_ZSHRC_BASE="${HOME}/.config/zsh/runcoms/base"
_ZSHRC_LOCAL="${HOME}/.config/zsh/runcoms/$HOST"

if [ -f $_ZSHRC_BASE ]; then
  source $_ZSHRC_BASE
fi

if [ -f $_ZSHRC_LOCAL ]; then
  source $_ZSHRC_LOCAL
fi

function cmd_exists() {
  whence -cp "$1" 2> /dev/null
}

function cmd_exists_bool() {
  return $+commands["$1"]
}

# thefuck
if [[ $(cmd_exists_bool thefuck) ]]; then
  eval $(thefuck --alias)
fi

# line added by conda-app
export PATH=/home/avmo/.micromamba/condabin/app:$PATH

# Not necessary if the python zsh module is initialized
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
